DELETE https://crudcrud.com/api/21cabcb415c549b7adf349e0e2ee3c27/student/66e7c32afe837603e816c2bb
Accept: application/json

###
GET https://crudcrud.com/api/21cabcb415c549b7adf349e0e2ee3c27/student
Accept: application/json

###
POST https://crudcrud.com/api/21cabcb415c549b7adf349e0e2ee3c27/student
Content-Type: application/json

{
  "name": "Sasha Osipov",
  "grade": 2
}