### POST request to example server
POST https://crudcrud.com/api/dc9f774f028a437c8a2211b187731689/unicorn
Content-Type: application/json

{
  "name": "Tiny",
  "tailColor": "green"
}

###
GET https://crudcrud.com/api/dc9f774f028a437c8a2211b187731689/unicorn/
Accept: application/json

###
DELETE https://crudcrud.com/api/dc9f774f028a437c8a2211b187731689/unicorn/66ea8dfbfe837603e816c64a
Accept: application/json

###
PUT https://crudcrud.com/api/dc9f774f028a437c8a2211b187731689/unicorn/66e3e51afe837603e816be02
Content-Type: application/json

{
  "name": "Tiny",
  "tailColor": "blue"
}

